-- suggestions テーブルの作成
-- AI が生成した英語表現の提案を格納します。1 つの AI メッセージ (chat_messages) に対して複数の提案が紐付きます。

CREATE TABLE IF NOT EXISTS public.suggestions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chat_message_id BIGINT NOT NULL REFERENCES public.chat_messages(id) ON DELETE CASCADE,
    english_sentence TEXT NOT NULL,
    japanese_translation TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- インデックスの作成
CREATE INDEX IF NOT EXISTS idx_suggestions_chat_message_id ON public.suggestions(chat_message_id);

-- RLSを有効化
ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;

-- suggestionsテーブルのポリシー
CREATE POLICY "Users can view suggestions for their messages" ON public.suggestions
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.chat_messages 
            WHERE id = chat_message_id 
            AND (user_id = auth.uid() OR user_id IS NULL)
        )
    );

CREATE POLICY "System can insert suggestions" ON public.suggestions
    FOR INSERT WITH CHECK (true);
