-- bookmarks テーブルの作成
-- ユーザーがブックマークした提案を管理します。profiles テーブルと suggestions テーブルの中間テーブルとして機能します。

CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    suggestion_id BIGINT NOT NULL REFERENCES public.suggestions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, suggestion_id)
);

-- インデックスの作成
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON public.bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_suggestion_id ON public.bookmarks(suggestion_id);

-- RLSを有効化
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

-- bookmarksテーブルのポリシー
CREATE POLICY "Users can view own bookmarks" ON public.bookmarks
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own bookmarks" ON public.bookmarks
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own bookmarks" ON public.bookmarks
    FOR DELETE USING (auth.uid() = user_id);
